version: 1.3.9
cache: true

endpoints:
  openAI:
    disabled: true
  assistants:
    disabled: true
  google:
    disabled: true
  anthropic:
    disabled: true
  custom:
    - name: "OpenRouter"
      apiKey: "${OPENROUTER_KEY}"
      baseURL: "https://openrouter.ai/api/v1"
      models:
        default:
          - "openrouter/auto"
        fetch: true
      titleConvo: true
      titleModel: "openrouter/auto"
      dropParams: ['stop']
      modelDisplayLabel: "OpenRouter"

memory:
  disabled: false  # Set to true to completely disable memory
  personalize: true  # Gives users the ability to toggle memory on/off, true by default
  tokenLimit: 2000  # Maximum tokens for memory storage
  messageWindowSize: 5  # Number of recent messages to consider
  agent:
    id: "agent_dTldmd9xi2VErAukhceRH"

mcpServers:
  homeassistant:
    type: streamable-http
    url: "${HASS_URL}/api/mcp"
    headers:
      Authorization: "Bearer ${HASS_TOKEN}"
